---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: "us-east-1"
    aws_access_key: ''
    aws_secret_key: ''
    cidr_block: "10.0.0.0/16"
    sub_cidr_block: "10.0.1.0/28"
    dest_subnet: "0.0.0.0/0"
    image: "ami-04b9e92b5572fa0d1"
    instance_type: "t2.micro"

  tasks:
  - name: create a VPC with dedicated tenancy and a couple of tags
    ec2_vpc_net:
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      name: My_VPC
      cidr_block: "{{ cidr_block}}"
    register: ec2_vpc_net

  - name: Create Internet Gateway
    ec2_vpc_igw:
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_id: "{{ ec2_vpc_net.vpc.id }}"
      state:  present
    register: igw_result

  - name: create VPC subnet
    ec2_vpc_subnet:
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_id: "{{ ec2_vpc_net.vpc.id }}"
      cidr: "{{ sub_cidr_block }}"
      map_public: yes
    register: subnet_result

  - name: create ec2 VPC public subnet route table
    ec2_vpc_route_table:
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_id: "{{ ec2_vpc_net.vpc.id }}"
      subnets: "{{ sub_cidr_block }}"

      routes:
        - dest: "{{ dest_subnet }}"
          gateway_id: "{{ igw_result.gateway_id }} "
    register: route_results

  - name: create ec2 security group
    ec2_group:
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_id: "{{ ec2_vpc_net.vpc.id }}"
      name: "AWS_security_group"
      description: "Open port 22"
      rules:
      - proto: tcp
        ports:
          - 22
        cidr_ip: " {{ dest_subnet }}"
        rule_desc: allow all on port 22
    register: sec_group_results

  - name: Create one key pair
    ec2_key:
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      name: Production-key
    register: key_pair_results

  - name: Create EC2 Instance (Ubuntu)
    ec2:
      region: "{{ region }}"
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      vpc_subnet_id: "{{ subnet_result.subnet.id }}"
      assign_public_ip: yes
      key_name: "{{ key_pair_results.key.name }}"
      instance_type: "{{ instance_type }}"
      image: "{{ image }}"
      wait: "yes"

    register: results

  - debug:
      var: results
